language: node_js

matrix:
  include:
    - node_js: 12
      addons:
        postgresql: "10"
      dist: bionic
    - node_js: 12
      addons:
        postgresql: "10"
      dist: xenial
    - node_js: 12
      addons:
        postgresql: "9.6"
      dist: xenial
    - node_js: 12
      addons:
        postgresql: "9.5"
      dist: xenial
    - node_js: 10
      addons:
        postgresql: "9.5"
      dist: xenial
    - node_js: 8
      addons:
        postgresql: "9.5"
      dist: xenial
    - node_js: 6
      addons:
        postgresql: "9.5"
      dist: xenial

before_script:
  - psql --user postgres --command "CREATE TABLE test_filestore(name TEXT, mtime BIGINT, sqno BIGSERIAL, size BIGINT, meta JSONB, data BYTEA, created TIMESTAMP WITH TIME ZONE, updated TIMESTAMP WITH TIME ZONE)"
  - psql --user postgres --command "ALTER  TABLE test_filestore ADD CONSTRAINT test_filestore_pkc PRIMARY KEY(name, mtime, sqno)"

env:
  - PGUSER=postgres PGDATABASE=postgres

script: npm test
